#!/bin/bash
#
# Copyright 2016-2017 HLRS, University of Stuttgart
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

#=============================================================================
#
#         FILE: prologue
#
#        USAGE: prologue <default PBS prologue.parallel parameters>
#
#  DESCRIPTION: Sets up IOcm and vRDMA, also job related snap telemetry
#               monitoring task is started. Further, a process is forked that
#               waits for the user prologue wrapper to indicate availability
#               of job related guests to be instantiated.
#
#      OPTIONS: Refer to Torque documentation.
# REQUIREMENTS: File is owned by root and permissions are set to 500.
#         BUGS: ---
#        NOTES: ---
#       AUTHOR: Nico Struckmann, struckmann@hlrs.de
#      COMPANY: HLRS, University of Stuttgart
#      VERSION: 0.2
#      CREATED:
#     REVISION: May 09th 2017
#
#    CHANGELOG
#         v0.2: refactoring and clean up
#
#=============================================================================

#============================================================================#
#                                                                            #
#                          GLOBAL CONFIGURATION                              #
#                                                                            #
#============================================================================#

# source the global profile, for getting DEBUG and TRACE flags if set
source /etc/profile.d/99-mikelangelo-hpc_stack.sh;

#
# source the global functions and configuration
# order below is as required, do not change
#
source "$VTORQUE_DIR/common/const.sh" $@;
source "$VTORQUE_DIR/common/config.sh";
source "$VTORQUE_DIR/common/root-functions.sh";


#============================================================================#
#                                                                            #
#                          SCRIPT CONFIGURATION                              #
#                                                                            #
#============================================================================#


#============================================================================#
#                                                                            #
#                               FUNCTIONS                                    #
#                                                                            #
#============================================================================#


#============================================================================#
#                                                                            #
#                                 MAIN                                       #
#                                                                            #
#============================================================================#

#
# we need to wait for the job dir, otherwise it is created by the first log msg
# and that causes a race-condition in vsub where the symlink is created for VM jobs
#
waitUntilJobDirIsAvailable;

# if we do not run a VM job, some env vars need to be changed
ensureProperSettings;

# logging
logInfoMsg "Root prologue script started";
logTraceMsg "Running prologue as '$(id)', file: '$(basename ${BASH_SOURCE[0]})'";
logTraceMsg "~~~~~~~~~~Environment_Start~~~~~~~~~~\n$(env)\n~~~~~~~~~~~Environment_End~~~~~~~~~~~";

# capture STDOUT/STDERR outputs to log file
captureOutputStreams;

# in case there was a script for this in the $TORQUE_HOME/mom_priv
# that has been renamed (by the Makefile) to *.orig, call it now
runScriptPreviouslyInPlace "$(basename ${BASH_SOURCE[0]})" $@;

# start snap job task
startSnapTask;

# VM job ?
if ! isVMJob; then
  logDebugMsg "Bare-metal job detected.";
else

  logDebugMsg "VM job detected.";

  # setup vRDMA
  setUPvRDMA_P1;

  # ram disk or shared FS ?
  if $USE_RAM_DISK; then
    createRAMDisk;
  else
    checkSharedFS;
  fi

  # spawn process for booting VMs and configuring IOcm, vRDMA
  spawnProcess;
fi

# print info
logInfoMsg "Root Prologue script finished";

# print the consumed time in debug mode
runTimeStats;

# run the job
exit 0;
