#!/bin/bash
#
# Copyright 2016-2017 HLRS, University of Stuttgart
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

#=============================================================================
#
#         FILE: qsub
#
#        USAGE: qsub <parameters>
#
#  DESCRIPTION: The purpose of this wrapper is to route job submits either to
#               Torque's cli tool 'qsub' or to vTorque's cli tool 'vsub'.
#               Job submissions containing a '-vm <key=value,..>' parameter
#               will be forwarded to vsub executing the jobs in a virtual 
#               machine instead of physical nodes.
#
#      OPTIONS: ---
# REQUIREMENTS: Torque's job submission cli 'qsub' is installed and configured.
#               PBS_QSUB_PATH is properly configured and file const.sh
#               is sourced before this file. Further, vsub wrapper can be found
#               via environment variable '$PATH'.
#         BUGS: ---
#        NOTES: ---
#       AUTHOR: Nico Struckmann, struckmann@hlrs.de
#      COMPANY: HLRS, University of Stuttgart
#      VERSION: 0.1
#      CREATED: May 12 2017
#     REVISION:
#
#    CHANGELOG
#
#=============================================================================

#
# Random uid to identify a job's corresponding files (vm jobs, only)
#
export RUID="$(echo $(date +%N) | sha256sum | cut -d ' ' -f1 | cut -c 1-15)";

source /etc/profile.d/99-mikelangelo-hpc_stack.sh;
source "$SCRIPT_BASE_DIR/common/const.sh";
source "$SCRIPT_BASE_DIR/common/config.sh";
source "$SCRIPT_BASE_DIR/common/functions.sh";

# does the job submission contain a '-vm' resource request ?
if [ -n "$(echo $@ | grep -iE '-vm |-listimages')" ]; then
  # yes, forward job submission request to vTorque's vsub
  logDebugMsg "VM job detected,forwarding to vTorque.";
  $SCRIPT_BASE_DIR/vsub $@;
else
  # no, forward to PBS qsub directly
  logDebugMsg "No vm job, forwarding to Torque.";
  logTraceMsg "qsub args:\n $@";
  $REAL_QSUB $@;
fi

exit $?;